services:
  db:
    container_name: ${CONTAINER_DB}
    image: ${MYSQL_IMAGE}
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - wordpress_network

  wordpress:
    container_name: ${CONTAINER_WP}
    depends_on:
      - db
    image: ${WORDPRESS_IMAGE}
    ports:
      - "${WORDPRESS_PORT}:80"
    restart: always
    volumes:
      - ./data/wp:/var/www/html
    environment:
      - TZ=${TZ}
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
